message:
    path:     /
    defaults: { _controller: "MyAppProjetBundle:Message:index" }

message_show:
    path:     /{id}/show
    defaults: { _controller: "MyAppProjetBundle:Message:show" }

message_new:
    path:     /new
    defaults: { _controller: "MyAppProjetBundle:Message:new" }

message_create:
    path:     /create
    defaults: { _controller: "MyAppProjetBundle:Message:create" }
    requirements: { _method: post }

message_edit:
    path:     /{id}/edit
    defaults: { _controller: "MyAppProjetBundle:Message:edit" }

message_update:
    path:     /{id}/update
    defaults: { _controller: "MyAppProjetBundle:Message:update" }
    requirements: { _method: post|put }

message_delete:
    path:     /{id}/delete
    defaults: { _controller: "MyAppProjetBundle:Message:delete" }
    requirements: { _method: post|delete }
