my_app_user_homepage:
    path:     /hello/{name}
    defaults: { _controller: MyAppUserBundle:Default:index }
my_app_login:
    path:   /login
    defaults:  { _controller: MyAppUserBundle:Default:login }